QuanLyBanDienThoai/Areas/Admin/Controllers/AdminCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using QuanLyBanDienThoai.Models;

namespace QuanLyBanDienThoai.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminCategoriesController : Controller
    {
        private readonly QlbanDienThoaiContext _context;

        public AdminCategoriesController(QlbanDienThoaiContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminCategories
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var lstCategories = _context.Categories.AsNoTracking().OrderByDescending(x => x.CatId);
            PagedList<Category> models = new PagedList<Category>(lstCategories, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CatId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/AdminCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: Admin/AdminCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CatId,CatName,Description,ParentId,Levels,Ordering,Published,Thumb,Title,Alias,MetaDesc,MetaKey,Cover,SchemaMarkup")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string imageName = Extension.Extension.ToUrlFriendly(category.CatName) + extension;
                    category.Thumb = await Helper.Utilities.UploadFile(fThumb, @"categories", imageName.ToLower());
                }
                if (string.IsNullOrEmpty(category.Thumb)) category.Thumb = "default.jpg";
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/AdminCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CatId,CatName,Description,ParentId,Levels,Ordering,Published,Thumb,Title,Alias,MetaDesc,MetaKey,Cover,SchemaMarkup")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != category.CatId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string imageName = Extension.Extension.ToUrlFriendly(category.CatName) + extension;
                        category.Thumb = await Helper.Utilities.UploadFile(fThumb, @"categories", imageName.ToLower());
                    }
                    if (string.IsNullOrEmpty(category.Thumb)) category.Thumb = "default.jpg";
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CatId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CatId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/AdminCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'QlbanDienThoaiContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.CatId == id)).GetValueOrDefault();
        }
    }
}

QuanLyBanDienThoai/Areas/Admin/Views/AdminCategories/Create.cshtml
@model QuanLyBanDienThoai.Models.Category

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminCategories" asp-action="Index">Danh Sách Danh Mục</a>

            <span class="breadcrumb-item active">Tạo mới Danh Mục</span>
        </nav>
    </div>
</div>
<form asp-controller="AdminCategories" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Tạo mới Danh Mục</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin Danh Mục</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Thông tin SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên Danh Mục</label>
                        <input type="text" class="form-control" asp-for="CatName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Ordering</label>
                        <input type="text" class="form-control" asp-for="Ordering">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb">
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="form-group d-flex align-items-center">
                        <div class="switch m-r-10">
                            <input type="checkbox" asp-for="Published">
                            <label for="Published"></label>
                        </div>
                        <label>Public</label>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Level</label>
                        <input type="text" class="form-control" asp-for="Levels">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input type="text" class="form-control" asp-for="Title" />
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc" />
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey" />
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">ParentID</label>
                        <input type="text" class="form-control" asp-for="ParentId" />
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">Alias</label>
                        <input type="text" class="form-control" asp-for="Alias" />
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Mô tả</label>
                        <input type="text" class="form-control" asp-for="Description">
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">SchemaMarkup</label>
                        <input type="text" class="form-control" asp-for="SchemaMarkup">
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Cover</label>
                        <input type="text" class="form-control" asp-for="Cover">
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>



@*
<h1>Create</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CatName" class="control-label"></label>
                <input asp-for="CatName" class="form-control" />
                <span asp-validation-for="CatName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParentId" class="control-label"></label>
                <input asp-for="ParentId" class="form-control" />
                <span asp-validation-for="ParentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Levels" class="control-label"></label>
                <input asp-for="Levels" class="form-control" />
                <span asp-validation-for="Levels" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ordering" class="control-label"></label>
                <input asp-for="Ordering" class="form-control" />
                <span asp-validation-for="Ordering" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Published" /> @Html.DisplayNameFor(model => model.Published)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Thumb" class="control-label"></label>
                <input asp-for="Thumb" class="form-control" />
                <span asp-validation-for="Thumb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alias" class="control-label"></label>
                <input asp-for="Alias" class="form-control" />
                <span asp-validation-for="Alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaDesc" class="control-label"></label>
                <input asp-for="MetaDesc" class="form-control" />
                <span asp-validation-for="MetaDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaKey" class="control-label"></label>
                <input asp-for="MetaKey" class="form-control" />
                <span asp-validation-for="MetaKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="control-label"></label>
                <input asp-for="Cover" class="form-control" />
                <span asp-validation-for="Cover" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SchemaMarkup" class="control-label"></label>
                <input asp-for="SchemaMarkup" class="form-control" />
                <span asp-validation-for="SchemaMarkup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

*@

QuanLyBanDienThoai/Areas/Admin/Views/AdminCategories/Delete.cshtml
@model QuanLyBanDienThoai.Models.Category

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminCategories" asp-action="Index">Danh Sách Danh Mục</a>

            <span class="breadcrumb-item active">Chi tiết Danh Mục : @Model.CatName </span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Xác nhận xoá danh mục : @Model.CatName</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.CatId</td>
                    </tr>
                    <tr>
                        <td>Tên Danh Mục:</td>
                        <td>@Model.CatName</td>
                    </tr>

                    <tr>
                        <td>Mô tả</td>
                        <td>@Model.Description</td>
                    </tr>

                    <tr>
                        <td>Public:</td>
                        <td>
                            @if (Model.Published == true)
                            {
                                <span class="badge badge-success">Active</span>
                            }
                            else
                            {
                                <span class="badge badge-danger">Deactive</span>
                            }
                        </td>
                    </tr>
                    <tr>
                        <td>Cover:</td>
                        <td>@Model.Cover</td>
                    </tr>

                    <tr>
                        <td>TIêu đề:</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <td>MetaDesc:</td>
                        <td>@Model.MetaDesc</td>
                    </tr>
                    <tr>
                        <td>MetaKey:</td>
                        <td>@Model.MetaKey</td>
                    </tr>
                    <tr>
                        <td>Alias:</td>
                        <td>@Model.Alias</td>
                    </tr>
                    <tr>
                        <td>SchemaMarkup:</td>
                        <td>@Model.SchemaMarkup</td>
                    </tr>
                    <tr>
                        <td>Ordering:</td>
                        <td>
                            @if (Model.Ordering == null)
                            {
                                <span class="badge badge-danger">Chưa có</span>
                            }
                            else
                            {
                                if (Model.Ordering == 1)
                                {
                                    <span class="badge badge-danger">Order</span>
                                }
                                else
                                {
                                    <span class="badge badge-danger">Unorder</span>
                                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td>Ảnh đại diện: @Model.Thumb</td>
                        <td>
                            <img width="200px" height="200px" src="~/images/categories/@Model.Thumb" alt="@Model.Title" />
                        </td>
                    </tr>
                    <tr>
                        <td>Xác nhận xoá</td>
                        <td>
                            <form asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@Model.CatId" method="post">
                                <input type="hidden" asp-for="CatId" />
                                <input type="submit" value="Xoá" class="btn btn-danger" />
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CatId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

QuanLyBanDienThoai/Areas/Admin/Views/AdminCategories/Details.cshtml
@model QuanLyBanDienThoai.Models.Category

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminCategories" asp-action="Index">Danh Sách Danh Mục</a>

            <span class="breadcrumb-item active">Chi tiết Danh Mục : @Model.CatName </span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin Danh Mục : @Model.CatName</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.CatId</td>
                    </tr>
                    <tr>
                        <td>Tên Danh Mục:</td>
                        <td>@Model.CatName</td>
                    </tr>

                    <tr>
                        <td>Mô tả</td>
                        <td>@Model.Description</td>
                    </tr>

                    <tr>
                        <td>Public:</td>
                        <td>
                            @if (Model.Published == true)
                            {
                                <span class="badge badge-success">Active</span>
                            }
                            else
                            {
                                <span class="badge badge-danger">Deactive</span>
                            }
                        </td>
                    </tr>
                    <tr>
                        <td>Cover:</td>
                        <td>@Model.Cover</td>
                    </tr>

                    <tr>
                        <td>TIêu đề:</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <td>MetaDesc:</td>
                        <td>@Model.MetaDesc</td>
                    </tr>
                    <tr>
                        <td>MetaKey:</td>
                        <td>@Model.MetaKey</td>
                    </tr>
                    <tr>
                        <td>Alias:</td>
                        <td>@Model.Alias</td>
                    </tr>
                    <tr>
                        <td>SchemaMarkup:</td>
                        <td>@Model.SchemaMarkup</td>
                    </tr>
                    <tr>
                        <td>Ordering:</td>
                        <td>
                            @if (Model.Ordering == null)
                            {
                                <span class="badge badge-danger">Chưa có</span>
                            }
                            else
                            {
                                if (Model.Ordering == 1)
                                {
                                    <span class="badge badge-danger">Order</span>
                                }
                                else
                                {
                                    <span class="badge badge-danger">Unorder</span>
                                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td>Ảnh đại diện: @Model.Thumb</td>
                        <td>
                            <img width="200px" height="200px" src="~/images/categories/@Model.Thumb" alt="@Model.Title" />
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CatId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

QuanLyBanDienThoai/Areas/Admin/Views/AdminCategories/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<QuanLyBanDienThoai.Models.Category>

@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Page" + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <h2 class="header-title">Orders List</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminCategories" asp-action="Index">Danh Sách Danh Mục</a>

            <span class="breadcrumb-item active">Danh sách Danh Mục : Page @CurrentPage </span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8"></div>
            <div class="col-lg-4 text-right">
                <a asp-area="Admin" asp-controller="AdminCategories" asp-action="Create" class="btn btn-primary">
                    <i class="anticon anticon-plus-circle m-r-5"></i>
                    <span>Add Categories</span>
                </a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>

                        <th>ID</th>
                        <th>Tên Danh Mục</th>
                        <th>Thạng thái</th>
                        <th>#</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            string url = $"/{@item.Alias}";
                            <tr>
                                
                                <td>
                                    @item.CatId
                                </td>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <img class="img-fluid rounded" src="assets/images/others/thumb-9.jpg" style="max-width: 60px" alt="">
                                        <h6 class="m-b-0 m-l-10">@item.CatName</h6>
                                    </div>
                                </td>
                                <td>
                                    @if (item.Published == true)
                                    {
                                        <span class="badge badge-success">Published</span>
                                    }
                                    else
                                    {
                                        <span class="badge badge-danger">Unpublished</span>
                                    }
                                </td>

                                <td>
                                    <a class="btn btn-primary m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Details" asp-route-id="@item.CatId">View</a>
                                    <a class="btn btn-secondary m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@item.CatId">Edit</a>
                                    <a class="btn btn-success m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@item.CatId">Delete</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminCategories" action="Index"></pager>
                </ul>
            </div>
        </div>
    </div>
</div>